#cloud-config
apt:
  sources:
    hashicorp:
      source: deb https://apt.releases.hashicorp.com noble main
      keyserver: https://apt.releases.hashicorp.com/gpg
      keyid: AA16FCBCA621E701
packages:
  - nomad
write_files:
  - path: /etc/nomad.d/nomad.hcl
    content: |
      data_dir  = "/var/lib/nomad"

      acl {
        enabled = true
      }

      advertise {
        http = "{{ GetPublicIP }}"
        rpc  = "{{ GetPublicIP }}"
        serf = "{{ GetPublicIP }}"
      }

      server {
        enabled          = true
        bootstrap_expect = 1 # should increase this after testing
      }
  - path: /usr/lib/systemd/system/nomad.service
    content: |
      [Unit]
      Description=Nomad
      Documentation=https://nomadproject.io/docs/
      Wants=network-online.target
      After=network-online.target

      [Service]
      # Nomad servers should be run as the "nomad" user.
      User=nomad
      Group=nomad

      Type=notify
      EnvironmentFile=-/etc/nomad.d/nomad.env
      ExecReload=/bin/kill -HUP $MAINPID
      ExecStart=/usr/bin/nomad agent -config /etc/nomad.d
      KillMode=process
      KillSignal=SIGINT
      LimitNOFILE=65536
      LimitNPROC=infinity
      Restart=on-failure
      RestartSec=2

      TasksMax=infinity

      # Nomad Server agents should never be force killed,
      # so here we disable OOM (out of memory) killing for this unit.
      OOMScoreAdjust=-1000

      [Install]
      WantedBy=multi-user.target
runcmd:
  - mkdir -p /var/lib/nomad
  - chown -R nomad:nomad /var/lib/nomad
  - systemctl enable nomad.service
  - systemctl start nomad.service
