#cloud-config
apt:
  sources:
    hashicorp:
      source: deb https://apt.releases.hashicorp.com noble main
      keyserver: https://apt.releases.hashicorp.com/gpg
      keyid: AA16FCBCA621E701
packages:
  - nomad
write_files:
  - path: /etc/nomad.d/nomad.hcl
    content: |
      data_dir  = "/var/lib/nomad"

      server {
        enabled          = true
        bootstrap_expect = 1 # should increase this after testing
      }
runcmd:
  - nomad agent -c /etc/nomad/server.conf.hcl
